package com.fontysxmaua.UniGuide.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Activity")
public class Activity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private Boolean isMandatory;

    @DynamoDBAttribute
    private Date startDate;

    @DynamoDBAttribute
    private Date endDate;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String room;

    @DynamoDBAttribute
    private String building;

    @DynamoDBAttribute
    private Integer capacity;

    @DynamoDBAttribute
    private Set<String> subscribed;

    @DynamoDBAttribute(attributeName = "attending")
    private Set<String> attending;

    @DynamoDBAttribute(attributeName = "lector")
    private String lector;

    public void addSubscribed(String email) {
        if (this.subscribed == null) {
            this.subscribed = new HashSet<>();
        }
        if (this.subscribed.size() < this.capacity){
            this.subscribed.add(email);
        }
    }

    public void removeSubscribed(String email){
        if (this.subscribed != null){
            this.subscribed.remove(email);
            if (this.subscribed.isEmpty()){
                this.subscribed = null;
            }
        }
    }


    public void addAttending(String email) {
        if (this.attending == null) {
            this.attending = new HashSet<>();
        }

        this.attending.add(email);
    }

//    @DynamoDBAttribute
//    private User creator;
}
