package com.fontysxmaua.UniGuide.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.LocalDate;
import java.util.Date;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Notification")
public class Notification {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String sender;

    @DynamoDBAttribute
    private String subject;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute(attributeName = "dateCreated")
    private Date dateCreated;
}
